version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/nginx.docker
    volumes:
      - ${DOCKER_PATH_PROJECT}:${DOCKER_PATH_CONTAINER}
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm/php-fpm.docker
    volumes:
      - ${DOCKER_PATH_PROJECT}:${DOCKER_PATH_CONTAINER}
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    links:
      - mysql
      - redis
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
    ports:
      - "127.0.0.1:9000-9001:9000-9001"
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ${DOCKER_PATH_PROJECT}:${DOCKER_PATH_CONTAINER}
    links:
      - mysql
      - redis
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
      - "COMPOSER_ALLOW_SUPERUSER=1"
    tty: true
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/database:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_DATABASE=laravel_users"
    ports:
      - "33061:3306"
  redis:
    image: redis
    ports:
      - "63791:6379"
  node:
    image: node:8.15-alpine
    volumes:
      - ${DOCKER_PATH_PROJECT}:${DOCKER_PATH_CONTAINER}
    working_dir: ${DOCKER_PATH_CONTAINER}
    tty: true

