version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ${DOCKER_PATH_PROJECT}:${DOCKER_PATH_CONTAINER}
    ports:
      - "8080:80"
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ${DOCKER_PATH_PROJECT}:${DOCKER_PATH_CONTAINER}
    links:
      - mysql
      - redis
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ${DOCKER_PATH_PROJECT}:${DOCKER_PATH_CONTAINER}
    links:
      - mysql
      - redis
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
    tty: true
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/database:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_DATABASE=elaravel"
    ports:
      - "33061:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080
  redis:
    image: redis
    ports:
      - "63791:6379"
  node:
    image: node:8.15-alpine
    volumes:
      - ${DOCKER_PATH_PROJECT}:${DOCKER_PATH_CONTAINER}
    working_dir: ${DOCKER_PATH_CONTAINER}
    tty: true

